#!/bin/bash
set -e

docker build -t sickp/centos-sshd:7 --pull versions/7
docker tag -f sickp/centos-sshd:7 sickp/centos-sshd:latest

examples=$(ls examples)
for tag in ${examples}; do
  docker build -t sickp/centos-sshd:${tag} examples/${tag}
done
